// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/favorite.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FavoriteActionRequest struct {
	VideoID              int64    `protobuf:"varint,1,opt,name=videoID,proto3" json:"videoID,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	ActionType           int64    `protobuf:"varint,3,opt,name=ActionType,proto3" json:"ActionType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FavoriteActionRequest) Reset()         { *m = FavoriteActionRequest{} }
func (m *FavoriteActionRequest) String() string { return proto.CompactTextString(m) }
func (*FavoriteActionRequest) ProtoMessage()    {}
func (*FavoriteActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_26b1c906da9dd176, []int{0}
}

func (m *FavoriteActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoriteActionRequest.Unmarshal(m, b)
}
func (m *FavoriteActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoriteActionRequest.Marshal(b, m, deterministic)
}
func (m *FavoriteActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoriteActionRequest.Merge(m, src)
}
func (m *FavoriteActionRequest) XXX_Size() int {
	return xxx_messageInfo_FavoriteActionRequest.Size(m)
}
func (m *FavoriteActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoriteActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FavoriteActionRequest proto.InternalMessageInfo

func (m *FavoriteActionRequest) GetVideoID() int64 {
	if m != nil {
		return m.VideoID
	}
	return 0
}

func (m *FavoriteActionRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *FavoriteActionRequest) GetActionType() int64 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

type FavoriteActionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FavoriteActionResponse) Reset()         { *m = FavoriteActionResponse{} }
func (m *FavoriteActionResponse) String() string { return proto.CompactTextString(m) }
func (*FavoriteActionResponse) ProtoMessage()    {}
func (*FavoriteActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_26b1c906da9dd176, []int{1}
}

func (m *FavoriteActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoriteActionResponse.Unmarshal(m, b)
}
func (m *FavoriteActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoriteActionResponse.Marshal(b, m, deterministic)
}
func (m *FavoriteActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoriteActionResponse.Merge(m, src)
}
func (m *FavoriteActionResponse) XXX_Size() int {
	return xxx_messageInfo_FavoriteActionResponse.Size(m)
}
func (m *FavoriteActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoriteActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FavoriteActionResponse proto.InternalMessageInfo

type FavoriteListRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FavoriteListRequest) Reset()         { *m = FavoriteListRequest{} }
func (m *FavoriteListRequest) String() string { return proto.CompactTextString(m) }
func (*FavoriteListRequest) ProtoMessage()    {}
func (*FavoriteListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_26b1c906da9dd176, []int{2}
}

func (m *FavoriteListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoriteListRequest.Unmarshal(m, b)
}
func (m *FavoriteListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoriteListRequest.Marshal(b, m, deterministic)
}
func (m *FavoriteListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoriteListRequest.Merge(m, src)
}
func (m *FavoriteListRequest) XXX_Size() int {
	return xxx_messageInfo_FavoriteListRequest.Size(m)
}
func (m *FavoriteListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoriteListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FavoriteListRequest proto.InternalMessageInfo

func (m *FavoriteListRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type FavoriteListResponse struct {
	List                 []int64  `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FavoriteListResponse) Reset()         { *m = FavoriteListResponse{} }
func (m *FavoriteListResponse) String() string { return proto.CompactTextString(m) }
func (*FavoriteListResponse) ProtoMessage()    {}
func (*FavoriteListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_26b1c906da9dd176, []int{3}
}

func (m *FavoriteListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoriteListResponse.Unmarshal(m, b)
}
func (m *FavoriteListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoriteListResponse.Marshal(b, m, deterministic)
}
func (m *FavoriteListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoriteListResponse.Merge(m, src)
}
func (m *FavoriteListResponse) XXX_Size() int {
	return xxx_messageInfo_FavoriteListResponse.Size(m)
}
func (m *FavoriteListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoriteListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FavoriteListResponse proto.InternalMessageInfo

func (m *FavoriteListResponse) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*FavoriteActionRequest)(nil), "pb.FavoriteActionRequest")
	proto.RegisterType((*FavoriteActionResponse)(nil), "pb.FavoriteActionResponse")
	proto.RegisterType((*FavoriteListRequest)(nil), "pb.FavoriteListRequest")
	proto.RegisterType((*FavoriteListResponse)(nil), "pb.FavoriteListResponse")
}

func init() {
	proto.RegisterFile("pb/favorite.proto", fileDescriptor_26b1c906da9dd176)
}

var fileDescriptor_26b1c906da9dd176 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x48, 0xd2, 0x4f,
	0x4b, 0x2c, 0xcb, 0x2f, 0xca, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a,
	0x48, 0x52, 0xca, 0xe4, 0x12, 0x75, 0x83, 0x8a, 0x3a, 0x26, 0x97, 0x64, 0xe6, 0xe7, 0x05, 0xa5,
	0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x70, 0xb1, 0x97, 0x65, 0xa6, 0xa4, 0xe6, 0x7b, 0xba,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0xc1, 0xb8, 0x42, 0x62, 0x5c, 0x6c, 0xa5, 0xc5, 0xa9,
	0x45, 0x9e, 0x2e, 0x12, 0x4c, 0x60, 0x09, 0x28, 0x4f, 0x48, 0x8e, 0x8b, 0x0b, 0x62, 0x44, 0x48,
	0x65, 0x41, 0xaa, 0x04, 0x33, 0x58, 0x0e, 0x49, 0x44, 0x49, 0x82, 0x4b, 0x0c, 0xdd, 0xaa, 0xe2,
	0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x25, 0x5d, 0x2e, 0x61, 0x98, 0x8c, 0x4f, 0x66, 0x71, 0x09, 0xcc,
	0x09, 0x08, 0x8b, 0x18, 0x91, 0x2d, 0x52, 0xd2, 0xe2, 0x12, 0x41, 0x55, 0x0e, 0x31, 0x46, 0x48,
	0x88, 0x8b, 0x25, 0x27, 0xb3, 0xb8, 0x44, 0x82, 0x51, 0x81, 0x59, 0x83, 0x39, 0x08, 0xcc, 0x36,
	0xea, 0x65, 0xe4, 0xe2, 0x87, 0x29, 0x0e, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xb2, 0xe7,
	0x62, 0x83, 0x38, 0x40, 0x48, 0x52, 0xaf, 0x20, 0x49, 0x0f, 0xab, 0xff, 0xa5, 0xa4, 0xb0, 0x49,
	0x41, 0x2d, 0xb2, 0xe4, 0x62, 0x01, 0x59, 0x2c, 0x24, 0x8e, 0xac, 0x06, 0xc9, 0xe5, 0x52, 0x12,
	0x98, 0x12, 0x10, 0xad, 0x4e, 0x6c, 0x51, 0x2c, 0x7a, 0xd6, 0x05, 0x49, 0x49, 0x6c, 0xe0, 0x28,
	0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xad, 0x30, 0x70, 0x97, 0x01, 0x00, 0x00,
}
