// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/favorite.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FavoriteActionRequest struct {
	VideoID              int64    `protobuf:"varint,1,opt,name=videoID,proto3" json:"videoID,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	ActionType           int64    `protobuf:"varint,3,opt,name=ActionType,proto3" json:"ActionType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FavoriteActionRequest) Reset()         { *m = FavoriteActionRequest{} }
func (m *FavoriteActionRequest) String() string { return proto.CompactTextString(m) }
func (*FavoriteActionRequest) ProtoMessage()    {}
func (*FavoriteActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_26b1c906da9dd176, []int{0}
}

func (m *FavoriteActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoriteActionRequest.Unmarshal(m, b)
}
func (m *FavoriteActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoriteActionRequest.Marshal(b, m, deterministic)
}
func (m *FavoriteActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoriteActionRequest.Merge(m, src)
}
func (m *FavoriteActionRequest) XXX_Size() int {
	return xxx_messageInfo_FavoriteActionRequest.Size(m)
}
func (m *FavoriteActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoriteActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FavoriteActionRequest proto.InternalMessageInfo

func (m *FavoriteActionRequest) GetVideoID() int64 {
	if m != nil {
		return m.VideoID
	}
	return 0
}

func (m *FavoriteActionRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *FavoriteActionRequest) GetActionType() int64 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

type FavoriteActionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FavoriteActionResponse) Reset()         { *m = FavoriteActionResponse{} }
func (m *FavoriteActionResponse) String() string { return proto.CompactTextString(m) }
func (*FavoriteActionResponse) ProtoMessage()    {}
func (*FavoriteActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_26b1c906da9dd176, []int{1}
}

func (m *FavoriteActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoriteActionResponse.Unmarshal(m, b)
}
func (m *FavoriteActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoriteActionResponse.Marshal(b, m, deterministic)
}
func (m *FavoriteActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoriteActionResponse.Merge(m, src)
}
func (m *FavoriteActionResponse) XXX_Size() int {
	return xxx_messageInfo_FavoriteActionResponse.Size(m)
}
func (m *FavoriteActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoriteActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FavoriteActionResponse proto.InternalMessageInfo

type FavoriteListRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FavoriteListRequest) Reset()         { *m = FavoriteListRequest{} }
func (m *FavoriteListRequest) String() string { return proto.CompactTextString(m) }
func (*FavoriteListRequest) ProtoMessage()    {}
func (*FavoriteListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_26b1c906da9dd176, []int{2}
}

func (m *FavoriteListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoriteListRequest.Unmarshal(m, b)
}
func (m *FavoriteListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoriteListRequest.Marshal(b, m, deterministic)
}
func (m *FavoriteListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoriteListRequest.Merge(m, src)
}
func (m *FavoriteListRequest) XXX_Size() int {
	return xxx_messageInfo_FavoriteListRequest.Size(m)
}
func (m *FavoriteListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoriteListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FavoriteListRequest proto.InternalMessageInfo

func (m *FavoriteListRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type FavoriteListResponse struct {
	List                 []int64  `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FavoriteListResponse) Reset()         { *m = FavoriteListResponse{} }
func (m *FavoriteListResponse) String() string { return proto.CompactTextString(m) }
func (*FavoriteListResponse) ProtoMessage()    {}
func (*FavoriteListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_26b1c906da9dd176, []int{3}
}

func (m *FavoriteListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoriteListResponse.Unmarshal(m, b)
}
func (m *FavoriteListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoriteListResponse.Marshal(b, m, deterministic)
}
func (m *FavoriteListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoriteListResponse.Merge(m, src)
}
func (m *FavoriteListResponse) XXX_Size() int {
	return xxx_messageInfo_FavoriteListResponse.Size(m)
}
func (m *FavoriteListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoriteListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FavoriteListResponse proto.InternalMessageInfo

func (m *FavoriteListResponse) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

type FavoriteIsFavRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	VideoID              int64    `protobuf:"varint,2,opt,name=videoID,proto3" json:"videoID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FavoriteIsFavRequest) Reset()         { *m = FavoriteIsFavRequest{} }
func (m *FavoriteIsFavRequest) String() string { return proto.CompactTextString(m) }
func (*FavoriteIsFavRequest) ProtoMessage()    {}
func (*FavoriteIsFavRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_26b1c906da9dd176, []int{4}
}

func (m *FavoriteIsFavRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoriteIsFavRequest.Unmarshal(m, b)
}
func (m *FavoriteIsFavRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoriteIsFavRequest.Marshal(b, m, deterministic)
}
func (m *FavoriteIsFavRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoriteIsFavRequest.Merge(m, src)
}
func (m *FavoriteIsFavRequest) XXX_Size() int {
	return xxx_messageInfo_FavoriteIsFavRequest.Size(m)
}
func (m *FavoriteIsFavRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoriteIsFavRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FavoriteIsFavRequest proto.InternalMessageInfo

func (m *FavoriteIsFavRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *FavoriteIsFavRequest) GetVideoID() int64 {
	if m != nil {
		return m.VideoID
	}
	return 0
}

type FavoriteIsFavResponse struct {
	IsFav                bool     `protobuf:"varint,1,opt,name=isFav,proto3" json:"isFav,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FavoriteIsFavResponse) Reset()         { *m = FavoriteIsFavResponse{} }
func (m *FavoriteIsFavResponse) String() string { return proto.CompactTextString(m) }
func (*FavoriteIsFavResponse) ProtoMessage()    {}
func (*FavoriteIsFavResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_26b1c906da9dd176, []int{5}
}

func (m *FavoriteIsFavResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FavoriteIsFavResponse.Unmarshal(m, b)
}
func (m *FavoriteIsFavResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FavoriteIsFavResponse.Marshal(b, m, deterministic)
}
func (m *FavoriteIsFavResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FavoriteIsFavResponse.Merge(m, src)
}
func (m *FavoriteIsFavResponse) XXX_Size() int {
	return xxx_messageInfo_FavoriteIsFavResponse.Size(m)
}
func (m *FavoriteIsFavResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FavoriteIsFavResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FavoriteIsFavResponse proto.InternalMessageInfo

func (m *FavoriteIsFavResponse) GetIsFav() bool {
	if m != nil {
		return m.IsFav
	}
	return false
}

func init() {
	proto.RegisterType((*FavoriteActionRequest)(nil), "pb.FavoriteActionRequest")
	proto.RegisterType((*FavoriteActionResponse)(nil), "pb.FavoriteActionResponse")
	proto.RegisterType((*FavoriteListRequest)(nil), "pb.FavoriteListRequest")
	proto.RegisterType((*FavoriteListResponse)(nil), "pb.FavoriteListResponse")
	proto.RegisterType((*FavoriteIsFavRequest)(nil), "pb.FavoriteIsFavRequest")
	proto.RegisterType((*FavoriteIsFavResponse)(nil), "pb.FavoriteIsFavResponse")
}

func init() {
	proto.RegisterFile("pb/favorite.proto", fileDescriptor_26b1c906da9dd176)
}

var fileDescriptor_26b1c906da9dd176 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x5f, 0x4b, 0xfb, 0x30,
	0x14, 0xa5, 0x7f, 0xd6, 0xdf, 0x8f, 0xfb, 0x22, 0x5e, 0xe7, 0xcc, 0xfa, 0x20, 0x23, 0x4f, 0x43,
	0x58, 0x05, 0x7d, 0x12, 0x05, 0x51, 0xc6, 0xb0, 0xe0, 0x53, 0xf5, 0xc9, 0xb7, 0x65, 0x46, 0x08,
	0xc8, 0x12, 0x9b, 0xac, 0xe0, 0x67, 0xf4, 0x4b, 0xc9, 0x92, 0x94, 0xa6, 0x5a, 0xf0, 0xad, 0xf7,
	0x9e, 0x93, 0x73, 0xee, 0x39, 0x14, 0x0e, 0x15, 0x3b, 0x7f, 0x5b, 0x37, 0xb2, 0x16, 0x86, 0x17,
	0xaa, 0x96, 0x46, 0x62, 0xac, 0x18, 0x15, 0x70, 0xbc, 0xf2, 0xdb, 0xbb, 0x8d, 0x11, 0x72, 0x5b,
	0xf1, 0x8f, 0x1d, 0xd7, 0x06, 0x09, 0xfc, 0x6b, 0xc4, 0x2b, 0x97, 0xe5, 0x92, 0x44, 0xb3, 0x68,
	0x9e, 0x54, 0xed, 0x88, 0x13, 0xc8, 0x76, 0x9a, 0xd7, 0xe5, 0x92, 0xc4, 0x16, 0xf0, 0x13, 0x9e,
	0x02, 0x38, 0x89, 0xe7, 0x4f, 0xc5, 0x49, 0x62, 0xb1, 0x60, 0x43, 0x09, 0x4c, 0x7e, 0x5a, 0x69,
	0x25, 0xb7, 0x9a, 0xd3, 0x05, 0x1c, 0xb5, 0xc8, 0xa3, 0xd0, 0xa6, 0x3d, 0xa1, 0x33, 0x8a, 0x42,
	0x23, 0x7a, 0x06, 0xe3, 0x3e, 0xdd, 0xc9, 0x20, 0x42, 0xfa, 0x2e, 0xb4, 0x21, 0xd1, 0x2c, 0x99,
	0x27, 0x95, 0xfd, 0xa6, 0x0f, 0x1d, 0xb7, 0xd4, 0xab, 0x75, 0xf3, 0x87, 0x76, 0x18, 0x3b, 0xee,
	0xc5, 0xa6, 0x8b, 0xae, 0x29, 0xaf, 0xe4, 0x6d, 0xc7, 0x30, 0x12, 0xfb, 0x85, 0x55, 0xfa, 0x5f,
	0xb9, 0xe1, 0xe2, 0x2b, 0x82, 0x83, 0x96, 0xff, 0xc4, 0xeb, 0x46, 0x6c, 0x38, 0xde, 0x42, 0xe6,
	0x92, 0xe3, 0xb4, 0x50, 0xac, 0x18, 0x2c, 0x3e, 0xcf, 0x87, 0x20, 0x6f, 0x75, 0x05, 0xe9, 0x3e,
	0x31, 0x9e, 0x84, 0x9c, 0xa0, 0xb2, 0x9c, 0xfc, 0x06, 0xfc, 0xd3, 0x1b, 0x18, 0xd9, 0xb3, 0xb1,
	0x47, 0x09, 0x3b, 0xc9, 0xa7, 0x03, 0x88, 0x7b, 0x7d, 0x9f, 0xbd, 0xa4, 0xc5, 0xb5, 0x62, 0x2c,
	0xb3, 0x7f, 0xce, 0xe5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0xee, 0xcd, 0x83, 0x4e, 0x02,
	0x00, 0x00,
}
