// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/publish.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PublishActionRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	AuthorID             int64    `protobuf:"varint,2,opt,name=authorID,proto3" json:"authorID,omitempty"`
	PlayUrl              string   `protobuf:"bytes,3,opt,name=playUrl,proto3" json:"playUrl,omitempty"`
	CoverUrl             string   `protobuf:"bytes,4,opt,name=coverUrl,proto3" json:"coverUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishActionRequest) Reset()         { *m = PublishActionRequest{} }
func (m *PublishActionRequest) String() string { return proto.CompactTextString(m) }
func (*PublishActionRequest) ProtoMessage()    {}
func (*PublishActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5349e40d701e15c2, []int{0}
}

func (m *PublishActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishActionRequest.Unmarshal(m, b)
}
func (m *PublishActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishActionRequest.Marshal(b, m, deterministic)
}
func (m *PublishActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishActionRequest.Merge(m, src)
}
func (m *PublishActionRequest) XXX_Size() int {
	return xxx_messageInfo_PublishActionRequest.Size(m)
}
func (m *PublishActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishActionRequest proto.InternalMessageInfo

func (m *PublishActionRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PublishActionRequest) GetAuthorID() int64 {
	if m != nil {
		return m.AuthorID
	}
	return 0
}

func (m *PublishActionRequest) GetPlayUrl() string {
	if m != nil {
		return m.PlayUrl
	}
	return ""
}

func (m *PublishActionRequest) GetCoverUrl() string {
	if m != nil {
		return m.CoverUrl
	}
	return ""
}

type PublishActionResponse struct {
	VideoID              int64    `protobuf:"varint,1,opt,name=VideoID,proto3" json:"VideoID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishActionResponse) Reset()         { *m = PublishActionResponse{} }
func (m *PublishActionResponse) String() string { return proto.CompactTextString(m) }
func (*PublishActionResponse) ProtoMessage()    {}
func (*PublishActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5349e40d701e15c2, []int{1}
}

func (m *PublishActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishActionResponse.Unmarshal(m, b)
}
func (m *PublishActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishActionResponse.Marshal(b, m, deterministic)
}
func (m *PublishActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishActionResponse.Merge(m, src)
}
func (m *PublishActionResponse) XXX_Size() int {
	return xxx_messageInfo_PublishActionResponse.Size(m)
}
func (m *PublishActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishActionResponse proto.InternalMessageInfo

func (m *PublishActionResponse) GetVideoID() int64 {
	if m != nil {
		return m.VideoID
	}
	return 0
}

type PublishListRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishListRequest) Reset()         { *m = PublishListRequest{} }
func (m *PublishListRequest) String() string { return proto.CompactTextString(m) }
func (*PublishListRequest) ProtoMessage()    {}
func (*PublishListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5349e40d701e15c2, []int{2}
}

func (m *PublishListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishListRequest.Unmarshal(m, b)
}
func (m *PublishListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishListRequest.Marshal(b, m, deterministic)
}
func (m *PublishListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishListRequest.Merge(m, src)
}
func (m *PublishListRequest) XXX_Size() int {
	return xxx_messageInfo_PublishListRequest.Size(m)
}
func (m *PublishListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishListRequest proto.InternalMessageInfo

func (m *PublishListRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type PublishListResponse struct {
	List                 []*Video `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishListResponse) Reset()         { *m = PublishListResponse{} }
func (m *PublishListResponse) String() string { return proto.CompactTextString(m) }
func (*PublishListResponse) ProtoMessage()    {}
func (*PublishListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5349e40d701e15c2, []int{3}
}

func (m *PublishListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishListResponse.Unmarshal(m, b)
}
func (m *PublishListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishListResponse.Marshal(b, m, deterministic)
}
func (m *PublishListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishListResponse.Merge(m, src)
}
func (m *PublishListResponse) XXX_Size() int {
	return xxx_messageInfo_PublishListResponse.Size(m)
}
func (m *PublishListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishListResponse proto.InternalMessageInfo

func (m *PublishListResponse) GetList() []*Video {
	if m != nil {
		return m.List
	}
	return nil
}

type PublishBatchGetRequest struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=Ids,proto3" json:"Ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishBatchGetRequest) Reset()         { *m = PublishBatchGetRequest{} }
func (m *PublishBatchGetRequest) String() string { return proto.CompactTextString(m) }
func (*PublishBatchGetRequest) ProtoMessage()    {}
func (*PublishBatchGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5349e40d701e15c2, []int{4}
}

func (m *PublishBatchGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishBatchGetRequest.Unmarshal(m, b)
}
func (m *PublishBatchGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishBatchGetRequest.Marshal(b, m, deterministic)
}
func (m *PublishBatchGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishBatchGetRequest.Merge(m, src)
}
func (m *PublishBatchGetRequest) XXX_Size() int {
	return xxx_messageInfo_PublishBatchGetRequest.Size(m)
}
func (m *PublishBatchGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishBatchGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishBatchGetRequest proto.InternalMessageInfo

func (m *PublishBatchGetRequest) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type PublishBatchGetResponse struct {
	List                 []*Video `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishBatchGetResponse) Reset()         { *m = PublishBatchGetResponse{} }
func (m *PublishBatchGetResponse) String() string { return proto.CompactTextString(m) }
func (*PublishBatchGetResponse) ProtoMessage()    {}
func (*PublishBatchGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5349e40d701e15c2, []int{5}
}

func (m *PublishBatchGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishBatchGetResponse.Unmarshal(m, b)
}
func (m *PublishBatchGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishBatchGetResponse.Marshal(b, m, deterministic)
}
func (m *PublishBatchGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishBatchGetResponse.Merge(m, src)
}
func (m *PublishBatchGetResponse) XXX_Size() int {
	return xxx_messageInfo_PublishBatchGetResponse.Size(m)
}
func (m *PublishBatchGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishBatchGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishBatchGetResponse proto.InternalMessageInfo

func (m *PublishBatchGetResponse) GetList() []*Video {
	if m != nil {
		return m.List
	}
	return nil
}

type Video struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	AuthorId             int64    `protobuf:"varint,2,opt,name=AuthorId,proto3" json:"AuthorId,omitempty"`
	PlayUrl              string   `protobuf:"bytes,3,opt,name=PlayUrl,proto3" json:"PlayUrl,omitempty"`
	CoverUrl             string   `protobuf:"bytes,4,opt,name=CoverUrl,proto3" json:"CoverUrl,omitempty"`
	FavoriteCount        int64    `protobuf:"varint,5,opt,name=FavoriteCount,proto3" json:"FavoriteCount,omitempty"`
	CommentCount         int64    `protobuf:"varint,6,opt,name=CommentCount,proto3" json:"CommentCount,omitempty"`
	Title                string   `protobuf:"bytes,7,opt,name=Title,proto3" json:"Title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Video) Reset()         { *m = Video{} }
func (m *Video) String() string { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()    {}
func (*Video) Descriptor() ([]byte, []int) {
	return fileDescriptor_5349e40d701e15c2, []int{6}
}

func (m *Video) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Video.Unmarshal(m, b)
}
func (m *Video) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Video.Marshal(b, m, deterministic)
}
func (m *Video) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Video.Merge(m, src)
}
func (m *Video) XXX_Size() int {
	return xxx_messageInfo_Video.Size(m)
}
func (m *Video) XXX_DiscardUnknown() {
	xxx_messageInfo_Video.DiscardUnknown(m)
}

var xxx_messageInfo_Video proto.InternalMessageInfo

func (m *Video) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Video) GetAuthorId() int64 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func (m *Video) GetPlayUrl() string {
	if m != nil {
		return m.PlayUrl
	}
	return ""
}

func (m *Video) GetCoverUrl() string {
	if m != nil {
		return m.CoverUrl
	}
	return ""
}

func (m *Video) GetFavoriteCount() int64 {
	if m != nil {
		return m.FavoriteCount
	}
	return 0
}

func (m *Video) GetCommentCount() int64 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *Video) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*PublishActionRequest)(nil), "pb.PublishActionRequest")
	proto.RegisterType((*PublishActionResponse)(nil), "pb.PublishActionResponse")
	proto.RegisterType((*PublishListRequest)(nil), "pb.PublishListRequest")
	proto.RegisterType((*PublishListResponse)(nil), "pb.PublishListResponse")
	proto.RegisterType((*PublishBatchGetRequest)(nil), "pb.PublishBatchGetRequest")
	proto.RegisterType((*PublishBatchGetResponse)(nil), "pb.PublishBatchGetResponse")
	proto.RegisterType((*Video)(nil), "pb.Video")
}

func init() {
	proto.RegisterFile("pb/publish.proto", fileDescriptor_5349e40d701e15c2)
}

var fileDescriptor_5349e40d701e15c2 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0xeb, 0xd3, 0x40,
	0x10, 0x25, 0x1f, 0x4d, 0xdb, 0x51, 0x4b, 0x59, 0x6b, 0x1b, 0x23, 0x42, 0x09, 0x1e, 0x8a, 0x48,
	0xc4, 0x2a, 0x28, 0x88, 0x87, 0x36, 0x45, 0x09, 0x78, 0x28, 0xf1, 0xe3, 0xe0, 0x2d, 0x1f, 0x0b,
	0x5d, 0x48, 0xb3, 0x6b, 0x76, 0x53, 0xf0, 0xe2, 0xff, 0xe7, 0xc1, 0xff, 0x49, 0x76, 0xb3, 0x89,
	0x4d, 0xdb, 0xc3, 0xef, 0x96, 0x37, 0xf3, 0xde, 0xcc, 0xe4, 0xcd, 0x2c, 0x4c, 0x59, 0xfa, 0x92,
	0xd5, 0x69, 0x41, 0xf8, 0x21, 0x60, 0x15, 0x15, 0x14, 0x99, 0x2c, 0xf5, 0x7f, 0xc3, 0x6c, 0xdf,
	0x04, 0x37, 0x99, 0x20, 0xb4, 0x8c, 0xf1, 0xcf, 0x1a, 0x73, 0x81, 0x66, 0x30, 0x10, 0x44, 0x14,
	0xd8, 0x35, 0x96, 0xc6, 0x6a, 0x1c, 0x37, 0x00, 0x79, 0x30, 0x4a, 0x6a, 0x71, 0xa0, 0x55, 0xb4,
	0x73, 0xcd, 0xa5, 0xb1, 0xb2, 0xe2, 0x0e, 0x23, 0x17, 0x86, 0xac, 0x48, 0x7e, 0x7d, 0xab, 0x0a,
	0xd7, 0x52, 0x9a, 0x16, 0x4a, 0x55, 0x46, 0x4f, 0xb8, 0x92, 0x29, 0x5b, 0xa5, 0x3a, 0xec, 0xbf,
	0x82, 0x47, 0x17, 0xfd, 0x39, 0xa3, 0x25, 0xc7, 0xb2, 0xdc, 0x77, 0x92, 0x63, 0x1a, 0xed, 0xd4,
	0x08, 0x56, 0xdc, 0x42, 0xff, 0x05, 0x20, 0x2d, 0xf9, 0x4c, 0xb8, 0x68, 0x07, 0x9e, 0x83, 0x53,
	0x73, 0x5c, 0x75, 0x74, 0x8d, 0xfc, 0x37, 0xf0, 0xb0, 0xc7, 0xd6, 0xe5, 0x9f, 0x82, 0x5d, 0x10,
	0x2e, 0x5c, 0x63, 0x69, 0xad, 0xee, 0xad, 0xc7, 0x01, 0x4b, 0x03, 0x55, 0x3f, 0x56, 0x61, 0xff,
	0x39, 0xcc, 0xb5, 0x6a, 0x9b, 0x88, 0xec, 0xf0, 0x09, 0x77, 0x7d, 0xa6, 0x60, 0x45, 0x39, 0x57,
	0x3a, 0x2b, 0x96, 0x9f, 0xfe, 0x3b, 0x58, 0x5c, 0x71, 0xef, 0xd6, 0xe5, 0x8f, 0x01, 0x03, 0x85,
	0xd1, 0x04, 0xcc, 0x28, 0xd7, 0x93, 0x9b, 0x51, 0x2e, 0x2d, 0xdb, 0x34, 0xc6, 0xe6, 0xad, 0xd1,
	0x2d, 0x96, 0xce, 0xec, 0xfb, 0x46, 0xef, 0xff, 0x1b, 0x1d, 0x5e, 0x18, 0xdd, 0x62, 0xf4, 0x0c,
	0x1e, 0x7c, 0x4c, 0x4e, 0xb4, 0x22, 0x02, 0x87, 0xb4, 0x2e, 0x85, 0x3b, 0x50, 0x65, 0xfb, 0x41,
	0xe4, 0xc3, 0xfd, 0x90, 0x1e, 0x8f, 0xb8, 0x14, 0x0d, 0xc9, 0x51, 0xa4, 0x5e, 0x4c, 0x9e, 0xc6,
	0x57, 0x75, 0x1a, 0xc3, 0xe6, 0x34, 0x14, 0x58, 0xff, 0x35, 0x60, 0xa2, 0x6d, 0xf8, 0x82, 0xab,
	0x13, 0xc9, 0x30, 0xfa, 0x00, 0x4e, 0xb3, 0x54, 0xe4, 0xca, 0x3f, 0xbf, 0x75, 0x67, 0xde, 0xe3,
	0x1b, 0x19, 0x6d, 0xde, 0x5b, 0xb0, 0xe5, 0xca, 0xd0, 0xfc, 0x8c, 0x72, 0xb6, 0x71, 0x6f, 0x71,
	0x15, 0xd7, 0xc2, 0x10, 0x46, 0xed, 0x26, 0x90, 0x77, 0x46, 0xba, 0x58, 0xa5, 0xf7, 0xe4, 0x66,
	0xae, 0x29, 0xb2, 0x75, 0x7e, 0xd8, 0xc1, 0x7b, 0x96, 0xa6, 0x8e, 0x7a, 0x2b, 0xaf, 0xff, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xd8, 0xcf, 0xd7, 0xa3, 0x3f, 0x03, 0x00, 0x00,
}
