// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/relation.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RelationActionRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	FollowID             int64    `protobuf:"varint,2,opt,name=followID,proto3" json:"followID,omitempty"`
	ActionType           int32    `protobuf:"varint,3,opt,name=ActionType,proto3" json:"ActionType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelationActionRequest) Reset()         { *m = RelationActionRequest{} }
func (m *RelationActionRequest) String() string { return proto.CompactTextString(m) }
func (*RelationActionRequest) ProtoMessage()    {}
func (*RelationActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec642126eb9adff, []int{0}
}

func (m *RelationActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationActionRequest.Unmarshal(m, b)
}
func (m *RelationActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationActionRequest.Marshal(b, m, deterministic)
}
func (m *RelationActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationActionRequest.Merge(m, src)
}
func (m *RelationActionRequest) XXX_Size() int {
	return xxx_messageInfo_RelationActionRequest.Size(m)
}
func (m *RelationActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RelationActionRequest proto.InternalMessageInfo

func (m *RelationActionRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *RelationActionRequest) GetFollowID() int64 {
	if m != nil {
		return m.FollowID
	}
	return 0
}

func (m *RelationActionRequest) GetActionType() int32 {
	if m != nil {
		return m.ActionType
	}
	return 0
}

type RelationActionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelationActionResponse) Reset()         { *m = RelationActionResponse{} }
func (m *RelationActionResponse) String() string { return proto.CompactTextString(m) }
func (*RelationActionResponse) ProtoMessage()    {}
func (*RelationActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec642126eb9adff, []int{1}
}

func (m *RelationActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationActionResponse.Unmarshal(m, b)
}
func (m *RelationActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationActionResponse.Marshal(b, m, deterministic)
}
func (m *RelationActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationActionResponse.Merge(m, src)
}
func (m *RelationActionResponse) XXX_Size() int {
	return xxx_messageInfo_RelationActionResponse.Size(m)
}
func (m *RelationActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RelationActionResponse proto.InternalMessageInfo

type RelationFollowListRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelationFollowListRequest) Reset()         { *m = RelationFollowListRequest{} }
func (m *RelationFollowListRequest) String() string { return proto.CompactTextString(m) }
func (*RelationFollowListRequest) ProtoMessage()    {}
func (*RelationFollowListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec642126eb9adff, []int{2}
}

func (m *RelationFollowListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationFollowListRequest.Unmarshal(m, b)
}
func (m *RelationFollowListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationFollowListRequest.Marshal(b, m, deterministic)
}
func (m *RelationFollowListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationFollowListRequest.Merge(m, src)
}
func (m *RelationFollowListRequest) XXX_Size() int {
	return xxx_messageInfo_RelationFollowListRequest.Size(m)
}
func (m *RelationFollowListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationFollowListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RelationFollowListRequest proto.InternalMessageInfo

func (m *RelationFollowListRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type RelationFollowListResponse struct {
	FollowIDList         []int64  `protobuf:"varint,1,rep,packed,name=followIDList,proto3" json:"followIDList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelationFollowListResponse) Reset()         { *m = RelationFollowListResponse{} }
func (m *RelationFollowListResponse) String() string { return proto.CompactTextString(m) }
func (*RelationFollowListResponse) ProtoMessage()    {}
func (*RelationFollowListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec642126eb9adff, []int{3}
}

func (m *RelationFollowListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationFollowListResponse.Unmarshal(m, b)
}
func (m *RelationFollowListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationFollowListResponse.Marshal(b, m, deterministic)
}
func (m *RelationFollowListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationFollowListResponse.Merge(m, src)
}
func (m *RelationFollowListResponse) XXX_Size() int {
	return xxx_messageInfo_RelationFollowListResponse.Size(m)
}
func (m *RelationFollowListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationFollowListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RelationFollowListResponse proto.InternalMessageInfo

func (m *RelationFollowListResponse) GetFollowIDList() []int64 {
	if m != nil {
		return m.FollowIDList
	}
	return nil
}

type RelationFollowerListRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelationFollowerListRequest) Reset()         { *m = RelationFollowerListRequest{} }
func (m *RelationFollowerListRequest) String() string { return proto.CompactTextString(m) }
func (*RelationFollowerListRequest) ProtoMessage()    {}
func (*RelationFollowerListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec642126eb9adff, []int{4}
}

func (m *RelationFollowerListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationFollowerListRequest.Unmarshal(m, b)
}
func (m *RelationFollowerListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationFollowerListRequest.Marshal(b, m, deterministic)
}
func (m *RelationFollowerListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationFollowerListRequest.Merge(m, src)
}
func (m *RelationFollowerListRequest) XXX_Size() int {
	return xxx_messageInfo_RelationFollowerListRequest.Size(m)
}
func (m *RelationFollowerListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationFollowerListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RelationFollowerListRequest proto.InternalMessageInfo

func (m *RelationFollowerListRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type RelationFollowerListResponse struct {
	FollowerIDList       []int64  `protobuf:"varint,1,rep,packed,name=followerIDList,proto3" json:"followerIDList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelationFollowerListResponse) Reset()         { *m = RelationFollowerListResponse{} }
func (m *RelationFollowerListResponse) String() string { return proto.CompactTextString(m) }
func (*RelationFollowerListResponse) ProtoMessage()    {}
func (*RelationFollowerListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ec642126eb9adff, []int{5}
}

func (m *RelationFollowerListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationFollowerListResponse.Unmarshal(m, b)
}
func (m *RelationFollowerListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationFollowerListResponse.Marshal(b, m, deterministic)
}
func (m *RelationFollowerListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationFollowerListResponse.Merge(m, src)
}
func (m *RelationFollowerListResponse) XXX_Size() int {
	return xxx_messageInfo_RelationFollowerListResponse.Size(m)
}
func (m *RelationFollowerListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationFollowerListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RelationFollowerListResponse proto.InternalMessageInfo

func (m *RelationFollowerListResponse) GetFollowerIDList() []int64 {
	if m != nil {
		return m.FollowerIDList
	}
	return nil
}

func init() {
	proto.RegisterType((*RelationActionRequest)(nil), "pb.RelationActionRequest")
	proto.RegisterType((*RelationActionResponse)(nil), "pb.RelationActionResponse")
	proto.RegisterType((*RelationFollowListRequest)(nil), "pb.RelationFollowListRequest")
	proto.RegisterType((*RelationFollowListResponse)(nil), "pb.RelationFollowListResponse")
	proto.RegisterType((*RelationFollowerListRequest)(nil), "pb.RelationFollowerListRequest")
	proto.RegisterType((*RelationFollowerListResponse)(nil), "pb.RelationFollowerListResponse")
}

func init() {
	proto.RegisterFile("pb/relation.proto", fileDescriptor_9ec642126eb9adff)
}

var fileDescriptor_9ec642126eb9adff = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x48, 0xd2, 0x2f,
	0x4a, 0xcd, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a,
	0x48, 0x52, 0xca, 0xe6, 0x12, 0x0d, 0x82, 0x8a, 0x3a, 0x26, 0x83, 0xc8, 0xa0, 0xd4, 0xc2, 0xd2,
	0xd4, 0xe2, 0x12, 0x21, 0x31, 0x2e, 0xb6, 0xd2, 0xe2, 0xd4, 0x22, 0x4f, 0x17, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xe6, 0x20, 0x28, 0x4f, 0x48, 0x8a, 0x8b, 0x23, 0x2d, 0x3f, 0x27, 0x27, 0xbf, 0xdc,
	0xd3, 0x45, 0x82, 0x09, 0x2c, 0x03, 0xe7, 0x0b, 0xc9, 0x71, 0x71, 0x41, 0x0c, 0x09, 0xa9, 0x2c,
	0x48, 0x95, 0x60, 0x56, 0x60, 0xd4, 0x60, 0x0d, 0x42, 0x12, 0x51, 0x92, 0xe0, 0x12, 0x43, 0xb7,
	0xac, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0xc9, 0x98, 0x4b, 0x12, 0x26, 0xe3, 0x06, 0x36, 0xcd,
	0x27, 0xb3, 0xb8, 0x84, 0x80, 0x53, 0x94, 0x1c, 0xb8, 0xa4, 0xb0, 0x69, 0x82, 0x18, 0x29, 0xa4,
	0xc4, 0xc5, 0x03, 0x73, 0x18, 0x48, 0x5c, 0x82, 0x51, 0x81, 0x59, 0x83, 0x39, 0x08, 0x45, 0x4c,
	0xc9, 0x94, 0x4b, 0x1a, 0xd5, 0x84, 0xd4, 0x22, 0x62, 0x2c, 0x76, 0xe3, 0x92, 0xc1, 0xae, 0x0d,
	0x6a, 0xb5, 0x1a, 0x17, 0x5f, 0x1a, 0x54, 0x1c, 0xc5, 0x72, 0x34, 0x51, 0xa3, 0x4f, 0x8c, 0x5c,
	0xfc, 0x30, 0x83, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0xec, 0xb9, 0xd8, 0x20, 0x61,
	0x23, 0x24, 0xa9, 0x57, 0x90, 0xa4, 0x87, 0x35, 0x72, 0xa4, 0xa4, 0xb0, 0x49, 0x41, 0x2d, 0xf7,
	0xe6, 0xe2, 0x42, 0x84, 0x86, 0x90, 0x2c, 0xb2, 0x4a, 0x8c, 0xa0, 0x95, 0x92, 0xc3, 0x25, 0x0d,
	0x35, 0x2c, 0x90, 0x8b, 0x07, 0xd9, 0x87, 0x42, 0xf2, 0x98, 0xea, 0x51, 0x82, 0x4c, 0x4a, 0x01,
	0xb7, 0x02, 0x88, 0x91, 0x4e, 0x6c, 0x51, 0x2c, 0x7a, 0xd6, 0x05, 0x49, 0x49, 0x6c, 0xe0, 0x44,
	0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xca, 0x60, 0xce, 0xc3, 0x99, 0x02, 0x00, 0x00,
}
