// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserLoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{0}
}

func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserGetRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SeeId                int64    `protobuf:"varint,2,opt,name=seeId,proto3" json:"seeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetRequest) Reset()         { *m = UserGetRequest{} }
func (m *UserGetRequest) String() string { return proto.CompactTextString(m) }
func (*UserGetRequest) ProtoMessage()    {}
func (*UserGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{1}
}

func (m *UserGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetRequest.Unmarshal(m, b)
}
func (m *UserGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetRequest.Marshal(b, m, deterministic)
}
func (m *UserGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetRequest.Merge(m, src)
}
func (m *UserGetRequest) XXX_Size() int {
	return xxx_messageInfo_UserGetRequest.Size(m)
}
func (m *UserGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetRequest proto.InternalMessageInfo

func (m *UserGetRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserGetRequest) GetSeeId() int64 {
	if m != nil {
		return m.SeeId
	}
	return 0
}

type UserGetResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	FollowCount          int64    `protobuf:"varint,3,opt,name=FollowCount,proto3" json:"FollowCount,omitempty"`
	FollowerCount        int64    `protobuf:"varint,4,opt,name=FollowerCount,proto3" json:"FollowerCount,omitempty"`
	IsFollow             bool     `protobuf:"varint,5,opt,name=IsFollow,proto3" json:"IsFollow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetResponse) Reset()         { *m = UserGetResponse{} }
func (m *UserGetResponse) String() string { return proto.CompactTextString(m) }
func (*UserGetResponse) ProtoMessage()    {}
func (*UserGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{2}
}

func (m *UserGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetResponse.Unmarshal(m, b)
}
func (m *UserGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetResponse.Marshal(b, m, deterministic)
}
func (m *UserGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetResponse.Merge(m, src)
}
func (m *UserGetResponse) XXX_Size() int {
	return xxx_messageInfo_UserGetResponse.Size(m)
}
func (m *UserGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetResponse proto.InternalMessageInfo

func (m *UserGetResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserGetResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserGetResponse) GetFollowCount() int64 {
	if m != nil {
		return m.FollowCount
	}
	return 0
}

func (m *UserGetResponse) GetFollowerCount() int64 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *UserGetResponse) GetIsFollow() bool {
	if m != nil {
		return m.IsFollow
	}
	return false
}

type UserLoginResponse struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginResponse) Reset()         { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()    {}
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{3}
}

func (m *UserLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginResponse.Unmarshal(m, b)
}
func (m *UserLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginResponse.Marshal(b, m, deterministic)
}
func (m *UserLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginResponse.Merge(m, src)
}
func (m *UserLoginResponse) XXX_Size() int {
	return xxx_messageInfo_UserLoginResponse.Size(m)
}
func (m *UserLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginResponse proto.InternalMessageInfo

func (m *UserLoginResponse) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type UserRegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterRequest) Reset()         { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()    {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{4}
}

func (m *UserRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterRequest.Unmarshal(m, b)
}
func (m *UserRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterRequest.Marshal(b, m, deterministic)
}
func (m *UserRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterRequest.Merge(m, src)
}
func (m *UserRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegisterRequest.Size(m)
}
func (m *UserRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterRequest proto.InternalMessageInfo

func (m *UserRegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserRegisterResponse struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterResponse) Reset()         { *m = UserRegisterResponse{} }
func (m *UserRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*UserRegisterResponse) ProtoMessage()    {}
func (*UserRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{5}
}

func (m *UserRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterResponse.Unmarshal(m, b)
}
func (m *UserRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterResponse.Marshal(b, m, deterministic)
}
func (m *UserRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterResponse.Merge(m, src)
}
func (m *UserRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_UserRegisterResponse.Size(m)
}
func (m *UserRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterResponse proto.InternalMessageInfo

func (m *UserRegisterResponse) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func init() {
	proto.RegisterType((*UserLoginRequest)(nil), "pb.UserLoginRequest")
	proto.RegisterType((*UserGetRequest)(nil), "pb.UserGetRequest")
	proto.RegisterType((*UserGetResponse)(nil), "pb.UserGetResponse")
	proto.RegisterType((*UserLoginResponse)(nil), "pb.UserLoginResponse")
	proto.RegisterType((*UserRegisterRequest)(nil), "pb.UserRegisterRequest")
	proto.RegisterType((*UserRegisterResponse)(nil), "pb.UserRegisterResponse")
}

func init() {
	proto.RegisterFile("pb/user.proto", fileDescriptor_c4f917211a932270)
}

var fileDescriptor_c4f917211a932270 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0x4d, 0x5b, 0x20, 0x7c, 0x43, 0xe0, 0xd3, 0x01, 0xb5, 0xe9, 0x89, 0x34, 0x1e, 0x48, 0x4c,
	0xd6, 0x44, 0xbd, 0x19, 0x3d, 0xa8, 0x91, 0xd4, 0xa8, 0x87, 0x35, 0x5e, 0xbc, 0x51, 0x99, 0x10,
	0x12, 0xec, 0xae, 0xbb, 0x8b, 0xfc, 0x16, 0xff, 0x86, 0xbf, 0xd0, 0xec, 0x6e, 0x8b, 0x80, 0xd1,
	0x8b, 0xa7, 0xf6, 0xbd, 0x79, 0xef, 0xcd, 0xcc, 0xee, 0x42, 0x5b, 0xe6, 0x87, 0x73, 0x4d, 0x8a,
	0x49, 0x25, 0x8c, 0xc0, 0x50, 0xe6, 0xe9, 0x0d, 0x6c, 0x3d, 0x6a, 0x52, 0xb7, 0x62, 0x32, 0x2d,
	0x38, 0xbd, 0xce, 0x49, 0x1b, 0x4c, 0xa0, 0x69, 0x55, 0xc5, 0xe8, 0x85, 0xe2, 0xa0, 0x1f, 0x0c,
	0xfe, 0xf1, 0x25, 0xb6, 0x35, 0x39, 0xd2, 0x7a, 0x21, 0xd4, 0x38, 0x0e, 0x7d, 0xad, 0xc2, 0xe9,
	0x39, 0x74, 0x6c, 0xd6, 0x90, 0x4c, 0x95, 0xb4, 0x0b, 0x0d, 0xeb, 0xcc, 0xae, 0x5c, 0x4e, 0xc4,
	0x4b, 0x84, 0x3d, 0xa8, 0x6b, 0xa2, 0xcc, 0x47, 0x44, 0xdc, 0x83, 0xf4, 0x3d, 0x80, 0xff, 0xcb,
	0x00, 0x2d, 0x45, 0xa1, 0x09, 0x3b, 0x10, 0x66, 0xe3, 0xd2, 0x1d, 0x66, 0x63, 0x44, 0xa8, 0xdd,
	0xdb, 0xb9, 0x7c, 0x6f, 0xf7, 0x8f, 0x7d, 0x68, 0x5d, 0x8b, 0xd9, 0x4c, 0x2c, 0x2e, 0xc5, 0xbc,
	0x30, 0x71, 0xe4, 0xc4, 0xab, 0x14, 0xee, 0x43, 0xdb, 0x43, 0x52, 0x5e, 0x53, 0x73, 0x9a, 0x75,
	0xd2, 0xee, 0x96, 0x69, 0x4f, 0xc5, 0xf5, 0x7e, 0x30, 0x68, 0xf2, 0x25, 0x4e, 0x0f, 0x60, 0x7b,
	0xe5, 0x9c, 0xca, 0xe1, 0x7e, 0x58, 0x2f, 0xbd, 0x83, 0xae, 0x15, 0x73, 0x9a, 0x4c, 0xb5, 0xb1,
	0xdf, 0xbf, 0x9d, 0x2b, 0x83, 0xde, 0x7a, 0xdc, 0xef, 0xed, 0x8f, 0x3e, 0x02, 0x68, 0x59, 0xc3,
	0x03, 0xa9, 0xb7, 0xe9, 0x33, 0xe1, 0x09, 0xd4, 0xdd, 0xdc, 0xd8, 0x63, 0x32, 0x67, 0x9b, 0xd7,
	0x9d, 0xec, 0x6c, 0xb0, 0x65, 0xfa, 0x19, 0x34, 0xab, 0x8e, 0xb8, 0x57, 0x49, 0x36, 0x56, 0x4a,
	0xe2, 0xef, 0x85, 0xd2, 0xce, 0x20, 0x1a, 0x92, 0x41, 0xac, 0x04, 0x5f, 0xaf, 0x22, 0xe9, 0xae,
	0x71, 0x5e, 0x7f, 0xd1, 0x78, 0xaa, 0xb1, 0x53, 0x99, 0xe7, 0x0d, 0xf7, 0x36, 0x8f, 0x3f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x78, 0x87, 0x22, 0xfb, 0xac, 0x02, 0x00, 0x00,
}
